[ClipPilot]
api_key = your_azure_api_key_here
api_url = https://your-resource-name.cognitiveservices.azure.com/openai/deployments/gpt-4.1-mini/chat/completions?api-version=2025-01-01-preview
hotkey = ctrl+shift+c
